"""add foto_perfil to User

Revision ID: d4eef99f9920
Revises: 71ac5caae07f
Create Date: 2025-10-07 14:47:11.044010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4eef99f9920'
down_revision = '71ac5caae07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
